// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSfT0E0CKUIy6pNU20gI-8gmLBAKw61x4',
    appId: '1:417042812882:web:ddd64b350dff5a4445c20b',
    messagingSenderId: '417042812882',
    projectId: 'campusconnect-ec170',
    authDomain: 'campusconnect-ec170.firebaseapp.com',
    storageBucket: 'campusconnect-ec170.firebasestorage.app',
    measurementId: 'G-P9J0DRESVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA91SdJ9ioXGZI_OL8rELuNsF8G-Dwh2iI',
    appId: '1:417042812882:android:071b9dd4d984fcdb45c20b',
    messagingSenderId: '417042812882',
    projectId: 'campusconnect-ec170',
    storageBucket: 'campusconnect-ec170.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Wk2uyBbb1AmIy1W9HhiULEsb3KTC-c8',
    appId: '1:417042812882:ios:d265984c4c5d43de45c20b',
    messagingSenderId: '417042812882',
    projectId: 'campusconnect-ec170',
    storageBucket: 'campusconnect-ec170.firebasestorage.app',
    iosBundleId: 'com.example.campusconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Wk2uyBbb1AmIy1W9HhiULEsb3KTC-c8',
    appId: '1:417042812882:ios:d265984c4c5d43de45c20b',
    messagingSenderId: '417042812882',
    projectId: 'campusconnect-ec170',
    storageBucket: 'campusconnect-ec170.firebasestorage.app',
    iosBundleId: 'com.example.campusconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSfT0E0CKUIy6pNU20gI-8gmLBAKw61x4',
    appId: '1:417042812882:web:d9bce47c8e9bf0d645c20b',
    messagingSenderId: '417042812882',
    projectId: 'campusconnect-ec170',
    authDomain: 'campusconnect-ec170.firebaseapp.com',
    storageBucket: 'campusconnect-ec170.firebasestorage.app',
    measurementId: 'G-V12CFPPNYY',
  );
}
